# Generated by Django 3.2.10 on 2021-12-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.CharField(max_length=350, unique=True)),
                ('feed_name', models.CharField(default='', max_length=250)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
