# Generated by Django 3.2.10 on 2022-02-02 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feedmessage_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmessage',
            name='link',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='feedmessage',
            name='published',
            field=models.DateField(default=datetime.date(2022, 2, 2)),
        ),
    ]
